export const formASchema = {
  name: "Form - A",
  rows: 5,
  columns: 2,
  fields: [
    {
      _uid: 1,
      name: "name",
      label: "Name",
      type: "input",
      rowSpan: 1,
      colSpan: 1,
    },
    {
      _uid: 2,
      name: "preferredName",
      label: "Preferred Name",
      type: "input",
      rowSpan: 1,
      colSpan: 1,
    },
    {
      _uid: 3,
      name: "address",
      label: "Address",
      type: "input",
      rowSpan: 1,
      colSpan: 2,
    },
    {
      _uid: 4,
      name: "email",
      label: "Email",
      type: "input",
      rowSpan: 1,
      colSpan: 1,
    },
    {
      _uid: 5,
      name: "phone",
      label: "Phone",
      type: "input",
      rowSpan: 1,
      colSpan: 1,
    },
    {
      _uid: 6,
      name: "city",
      label: "City",
      type: "input",
      rowSpan: 1,
      colSpan: 1,
    },
    {
      _uid: 7,
      name: "postalCode",
      label: "ZIP / Postal Code",
      type: "input",
      rowSpan: 1,
      colSpan: 1,
    },
    {
      _uid: 8,
      name: "state",
      label: "State",
      type: "dropdown",
      rowSpan: 1,
      colSpan: 1,
    },
    {
      _uid: 9,
      name: "country",
      label: "Country",
      type: "dropdown",
      rowSpan: 1,
      colSpan: 1,
    },
  ],
};
