export const formASchema = {
  name: "Form - A",
  rows: 4,
  columns: 3,
  fields: [
    {
      _uid: 1,
      name: "name",
      label: "Name",
      type: "input",
      rowSpan: 1,
      colSpan: 1,
      validations: [
        {
          type: "minLength",
          value: 5,
          message: "Name should be minimum of 5 characters",
        },
        {
          type: "maxLength",
          value: 20,
          message: "Name should be maximum of 20 characters",
        },
      ],
    },
    {
      _uid: 2,
      name: "preferredName",
      label: "Preferred Name",
      type: "input",
      rowSpan: 1,
      colSpan: 2,
    },
    {
      _uid: 3,
      name: "address",
      label: "Address",
      type: "input",
      rowSpan: 1,
      colSpan: 3,
    },
    {
      _uid: 4,
      name: "email",
      label: "Email",
      type: "input",
      rowSpan: 1,
      colSpan: 1,
    },
    {
      _uid: 5,
      name: "phone",
      label: "Phone",
      type: "input",
      rowSpan: 1,
      colSpan: 1,
    },
    {
      _uid: 6,
      name: "city",
      label: "City",
      type: "input",
      rowSpan: 1,
      colSpan: 1,
    },
    {
      _uid: 7,
      name: "postalCode",
      label: "ZIP / Postal Code",
      type: "input",
      rowSpan: 1,
      colSpan: 1,
    },
    {
      _uid: 8,
      name: "state",
      label: "State",
      type: "dropdown",
      rowSpan: 1,
      colSpan: 1,
      options: [
        { value: "KA", label: "Karnataka" },
        { value: "GJ", label: "Gujarat" },
      ],
    },
    {
      _uid: 9,
      name: "country",
      label: "Country",
      type: "dropdown",
      rowSpan: 1,
      colSpan: 1,
      options: [
        { value: "IN", label: "India" },
        { value: "UK", label: "United Kingdom" },
      ],
    },
  ],
};
